language: cpp
compiler: 
- gcc
- clang
os:
- linux
- osx
before_script:
  - cd build

script:
  - cmake ..
  - make
  - cp ../src/numbers.in src
  - cp ../src/1.txt typerANDviewer
  - ./src/lab
  - cp ./src/numbers.out ./src/typerANDviewer
  - cd src/typerANDviewer
  - ./typer 1.txt
  - cat 1.txt > echo
  - ./viewer 2.txt
  - cat 2.txt > echo
  