language: cpp
compiler: 
- gcc
- clang
os:
- linux
- osx
before_script:
  - sudo apt-get install libomp
  - cd build

script:
  - cmake ..
  - make
  - cp ../src/numbers.in src
  - cp ../src/1.txt src/typerANDviewer
  - cd src
  - ./lab
  - cp numbers.out typerANDviewer
  - cd typerANDviewer
  - ./typer 1.txt
  - echo | cat 1.txt
  - ./viewer 2.txt
  - echo | cat 2.txt
  