language: cpp
compiler: 
- gcc
os:
- linux
before_script:
  - cd build

script:
  - cmake ..
  - make
  - cd src/generator
  - ./generator n 20 out
  - cd ../
  - cp generator/out ./
  - ./solver out nextout
  - cp nextout typerANDviewer
  - cd typerANDviewer
  - ./viewer nextout watchout
  - echo | cat watchout
 
  